# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email_title', models.CharField(blank=True, max_length=120, null=True)),
                ('email_body', models.CharField(blank=True, max_length=120, null=True)),
                ('email_to', models.CharField(blank=True, max_length=120, null=True)),
                ('email_from', models.CharField(blank=True, max_length=120, null=True)),
                ('email_created', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
    ]
