# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-04 06:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appDatos', '0002_auto_20180604_0458'),
    ]

    operations = [
        migrations.CreateModel(
            name='SistemaPagoOnline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=120, null=True)),
                ('pago_folio', models.CharField(blank=True, max_length=120, null=True)),
                ('pago_articulo', models.CharField(blank=True, max_length=120, null=True)),
                ('pago_total', models.CharField(blank=True, max_length=120, null=True)),
                ('ticket_created', models.DateTimeField(auto_now_add=True)),
                ('mensaje', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TicketItem',
        ),
    ]
